apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-neferdataengineering-cert
  namespace: default  # Replace with your desired namespace
spec:
  secretName: neferdata-tls  # Secret will be created to store the certificate and key
  issuerRef:
    name: route53-cluster-issuer
    kind: ClusterIssuer
  commonName: "*.neferdataengineering.com"
  dnsNames:
  - "*.neferdataengineering.com"
  - "neferdataengineering.com"
  - "www.neferdataengineering.com"
  - "api.neferdataengineering.com"

