apiVersion: v1
kind: Service
metadata:
  name: actix-api-service
  labels:
    {{- include "neferdata.labels" . | nindent 4 }}
spec:
  type: {{ .Values.actixApi.service.type }}
  ports:
    - port: {{ .Values.actixApi.service.port }}
      targetPort: 8080
      protocol: TCP
      name: actixapiport
  selector:
    app: actix-api
